/* eslint global-require: 0 */

export const teams = {
  ru: { name: '俄罗斯', flag: require('./assets/flags/ru.svg') },
  sa: { name: '沙特阿拉伯', flag: require('./assets/flags/sa.svg') },
  eg: { name: '埃及', flag: require('./assets/flags/eg.svg') },
  uy: { name: '乌拉圭', flag: require('./assets/flags/uy.svg') },
  pt: { name: '葡萄牙', flag: require('./assets/flags/pt.svg') },
  es: { name: '西班牙', flag: require('./assets/flags/es.svg') },
  ma: { name: '摩洛哥', flag: require('./assets/flags/ma.svg') },
  ir: { name: '伊朗', flag: require('./assets/flags/ir.svg') },
  fr: { name: '法国', flag: require('./assets/flags/fr.svg') },
  au: { name: '澳大利亚', flag: require('./assets/flags/au.svg') },
  pe: { name: '秘鲁', flag: require('./assets/flags/pe.svg') },
  dk: { name: '丹麦', flag: require('./assets/flags/dk.svg') },
  ar: { name: '阿根廷', flag: require('./assets/flags/ar.svg') },
  is: { name: '冰岛', flag: require('./assets/flags/is.svg') },
  hr: { name: '克罗地亚', flag: require('./assets/flags/hr.svg') },
  ng: { name: '尼日利亚', flag: require('./assets/flags/ng.svg') },
  br: { name: '巴西', flag: require('./assets/flags/br.svg') },
  ch: { name: '瑞士', flag: require('./assets/flags/ch.svg') },
  cr: { name: '哥斯达黎加', flag: require('./assets/flags/cr.svg') },
  rs: { name: '塞尔维亚', flag: require('./assets/flags/rs.svg') },
  de: { name: '德国', flag: require('./assets/flags/de.svg') },
  mx: { name: '墨西哥', flag: require('./assets/flags/mx.svg') },
  se: { name: '瑞典', flag: require('./assets/flags/se.svg') },
  kr: { name: '韩国', flag: require('./assets/flags/kr.svg') },
  be: { name: '比利时', flag: require('./assets/flags/be.svg') },
  pa: { name: '巴拿马', flag: require('./assets/flags/pa.svg') },
  tn: { name: '突尼斯', flag: require('./assets/flags/tn.svg') },
  en: { name: '英格兰', flag: require('./assets/flags/gb-eng.svg') },
  pl: { name: '波兰', flag: require('./assets/flags/pl.svg') },
  sn: { name: '塞内加尔', flag: require('./assets/flags/sn.svg') },
  co: { name: '哥伦比亚', flag: require('./assets/flags/co.svg') },
  jp: { name: '日本', flag: require('./assets/flags/jp.svg') },
};

export const groups = {
  a: { name: 'A组', teams: [teams.ru, teams.sa, teams.eg, teams.uy] },
  b: { name: 'B组', teams: [teams.pt, teams.es, teams.ma, teams.ir] },
  c: { name: 'C组', teams: [teams.fr, teams.au, teams.pe, teams.dk] },
  d: { name: 'D组', teams: [teams.ar, teams.is, teams.hr, teams.ng] },
  e: { name: 'E组', teams: [teams.br, teams.ch, teams.cr, teams.rs] },
  f: { name: 'F组', teams: [teams.de, teams.mx, teams.se, teams.kr] },
  g: { name: 'G组', teams: [teams.be, teams.pa, teams.tn, teams.en] },
  h: { name: 'H组', teams: [teams.pl, teams.sn, teams.co, teams.jp] },
};
